configserver: true

---
spring:
  profiles: local
  cloud:
    config:
      uri: ${vcap.services.config-service.credentials.uri:http://localhost:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud
  cloud:
    config:
      uri: https://config-leagues.apps.techolution.mobi
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-leagues.apps.techolution.mobi/eureka/