configserver: true

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:127.0.0.1}
    nonSecurePort: ${vcap.services.eureka-service.credentials.port:80}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/